 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/waste-bank-recommender-system-fe:$COMMIT_SHA', '.', '--build-arg', 'VITE_BASE_URL=${_VITE_BASE_URL}']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'asia.gcr.io/$PROJECT_ID/waste-bank-recommender-system-fe:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'waste-bank-recommender-system-fe'
   - '--image'
   - 'asia.gcr.io/$PROJECT_ID/waste-bank-recommender-system-fe:$COMMIT_SHA'
   - '--region'
   - 'asia-southeast2'
 images:
 - 'asia.gcr.io/$PROJECT_ID/waste-bank-recommender-system-fe:$COMMIT_SHA'